cabal-version: 3.16
name: learn-haskell
version: 0.1.0.0
author: KOMOTO Keita
build-type: Simple

library
  exposed-modules:
    Chapter01
    Chapter02
    Chapter03
    Chapter04

  hs-source-dirs: app
  build-depends: base

test-suite test
  type: exitcode-stdio-1.0
  main-is: Driver.hs
  hs-source-dirs: test
  build-depends:
    base,
    learn-haskell,
    tasty,
    tasty-hunit,
    hedgehog,
    tasty-hedgehog,

  other-modules:
    Chapter01Test

  build-tool-depends:
    tasty-discover:tasty-discover

  ghc-options: -Wno-missing-signatures
